### ISSUE TITLE
No package matching 'libssl1.1' is available

### ISSUE THREAD

**Issue by sergeeximius** [buluma/ansible-role-gitlab_ce#13]
Ubuntu 22.04.2 LTS

root@1360225-cg75529:~# apt-cache search libssl
libssl-dev - Secure Sockets Layer toolkit - development files
libssl-doc - Secure Sockets Layer toolkit - development documentation
libssl3 - Secure Sockets Layer toolkit - shared libraries
perl-openssl-defaults - version compatibility baseline for Perl OpenSSL packages
cl-plus-ssl - Common Lisp interface to OpenSSL
dcmtk - OFFIS DICOM toolkit command line utilities
dlang-openssl - D version of the C headers for openssl
libdcmtk-dev - OFFIS DICOM toolkit development libraries and headers
libdcmtk16 - OFFIS DICOM toolkit runtime libraries
libssl-ocaml - OCaml bindings for OpenSSL (runtime)
libssl-ocaml-dev - OCaml bindings for OpenSSL
libssl-utils-clojure - library for SSL certificate management on the JVM
r-cran-openssl - GNU R toolkit for encryption, signatures and certificates based on OpenSSL

**Comment by buluma** [comment]
good call, this was replaced by libssl3 in ubuntu 22. New release updated

**Comment by buluma** [comment]
good call, this was replaced by libssl3 in ubuntu 22. New release updated
